/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`post_items_by_id_refresh`]
#[derive(Clone, Debug)]
pub struct PostItemsByIdRefreshParams {
    /// Item Id
    pub id: String,
    /// BaseRefreshRequest: 
    pub base_refresh_request: models::BaseRefreshRequest,
    /// Indicates if the refresh should occur recursively.
    pub recursive: Option<bool>,
    /// Specifies the metadata refresh mode
    pub metadata_refresh_mode: Option<models::MetadataRefreshMode>,
    /// Specifies the image refresh mode
    pub image_refresh_mode: Option<models::MetadataRefreshMode>,
    /// Determines if metadata should be replaced. Only applicable if mode is FullRefresh
    pub replace_all_metadata: Option<bool>,
    /// Determines if images should be replaced. Only applicable if mode is FullRefresh
    pub replace_all_images: Option<bool>
}


/// struct for typed errors of method [`post_items_by_id_refresh`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostItemsByIdRefreshError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}


/// Requires authentication as user
pub async fn post_items_by_id_refresh(configuration: &configuration::Configuration, params: PostItemsByIdRefreshParams) -> Result<(), Error<PostItemsByIdRefreshError>> {

    let uri_str = format!("{}/Items/{Id}/Refresh", configuration.base_path, Id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = params.recursive {
        req_builder = req_builder.query(&[("Recursive", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.metadata_refresh_mode {
        req_builder = req_builder.query(&[("MetadataRefreshMode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_refresh_mode {
        req_builder = req_builder.query(&[("ImageRefreshMode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.replace_all_metadata {
        req_builder = req_builder.query(&[("ReplaceAllMetadata", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.replace_all_images {
        req_builder = req_builder.query(&[("ReplaceAllImages", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.base_refresh_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PostItemsByIdRefreshError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

