/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_videos_by_id_by_streamfilename`]
#[derive(Clone, Debug)]
pub struct GetVideosByIdByStreamfilenameParams {
    pub stream_file_name: String,
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}

/// struct for passing parameters to the method [`get_videos_by_id_stream`]
#[derive(Clone, Debug)]
pub struct GetVideosByIdStreamParams {
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}

/// struct for passing parameters to the method [`get_videos_by_id_stream_by_container`]
#[derive(Clone, Debug)]
pub struct GetVideosByIdStreamByContainerParams {
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}

/// struct for passing parameters to the method [`head_videos_by_id_by_streamfilename`]
#[derive(Clone, Debug)]
pub struct HeadVideosByIdByStreamfilenameParams {
    pub stream_file_name: String,
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}

/// struct for passing parameters to the method [`head_videos_by_id_stream`]
#[derive(Clone, Debug)]
pub struct HeadVideosByIdStreamParams {
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}

/// struct for passing parameters to the method [`head_videos_by_id_stream_by_container`]
#[derive(Clone, Debug)]
pub struct HeadVideosByIdStreamByContainerParams {
    /// Item Id
    pub id: String,
    /// Container
    pub container: String,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100
    pub audio_sample_rate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
    pub max_audio_channels: Option<i32>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
    pub r#static: Option<bool>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. The maximum horizontal resolution of the encoded video.
    pub max_width: Option<i32>,
    /// Optional. The maximum vertical resolution of the encoded video.
    pub max_height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<models::SubtitleDeliveryMethod>,
    /// Optional.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
    pub video_codec: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>
}


/// struct for typed errors of method [`get_videos_by_id_by_streamfilename`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideosByIdByStreamfilenameError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_videos_by_id_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideosByIdStreamError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_videos_by_id_stream_by_container`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideosByIdStreamByContainerError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`head_videos_by_id_by_streamfilename`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadVideosByIdByStreamfilenameError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`head_videos_by_id_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadVideosByIdStreamError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`head_videos_by_id_stream_by_container`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadVideosByIdStreamByContainerError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}


/// Requires authentication as user
pub async fn get_videos_by_id_by_streamfilename(configuration: &configuration::Configuration, params: GetVideosByIdByStreamfilenameParams) -> Result<(), Error<GetVideosByIdByStreamfilenameError>> {

    let uri_str = format!("{}/Videos/{Id}/{StreamFileName}", configuration.base_path, StreamFileName=crate::apis::urlencode(params.stream_file_name), Id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("Container", &params.container.to_string())]);
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVideosByIdByStreamfilenameError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires authentication as user
pub async fn get_videos_by_id_stream(configuration: &configuration::Configuration, params: GetVideosByIdStreamParams) -> Result<(), Error<GetVideosByIdStreamError>> {

    let uri_str = format!("{}/Videos/{Id}/stream", configuration.base_path, Id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("Container", &params.container.to_string())]);
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVideosByIdStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires authentication as user
pub async fn get_videos_by_id_stream_by_container(configuration: &configuration::Configuration, params: GetVideosByIdStreamByContainerParams) -> Result<(), Error<GetVideosByIdStreamByContainerError>> {

    let uri_str = format!("{}/Videos/{Id}/stream.{Container}", configuration.base_path, Id=crate::apis::urlencode(params.id), Container=crate::apis::urlencode(params.container));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVideosByIdStreamByContainerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires authentication as user
pub async fn head_videos_by_id_by_streamfilename(configuration: &configuration::Configuration, params: HeadVideosByIdByStreamfilenameParams) -> Result<(), Error<HeadVideosByIdByStreamfilenameError>> {

    let uri_str = format!("{}/Videos/{Id}/{StreamFileName}", configuration.base_path, StreamFileName=crate::apis::urlencode(params.stream_file_name), Id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::HEAD, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("Container", &params.container.to_string())]);
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<HeadVideosByIdByStreamfilenameError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires authentication as user
pub async fn head_videos_by_id_stream(configuration: &configuration::Configuration, params: HeadVideosByIdStreamParams) -> Result<(), Error<HeadVideosByIdStreamError>> {

    let uri_str = format!("{}/Videos/{Id}/stream", configuration.base_path, Id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::HEAD, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("Container", &params.container.to_string())]);
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<HeadVideosByIdStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires authentication as user
pub async fn head_videos_by_id_stream_by_container(configuration: &configuration::Configuration, params: HeadVideosByIdStreamByContainerParams) -> Result<(), Error<HeadVideosByIdStreamByContainerError>> {

    let uri_str = format!("{}/Videos/{Id}/stream.{Container}", configuration.base_path, Id=crate::apis::urlencode(params.id), Container=crate::apis::urlencode(params.container));
    let mut req_builder = configuration.client.request(reqwest::Method::HEAD, &uri_str);

    if let Some(ref param_value) = params.device_profile_id {
        req_builder = req_builder.query(&[("DeviceProfileId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("DeviceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("AudioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_auto_stream_copy {
        req_builder = req_builder.query(&[("EnableAutoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_sample_rate {
        req_builder = req_builder.query(&[("AudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("AudioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_channels {
        req_builder = req_builder.query(&[("AudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("MaxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#static {
        req_builder = req_builder.query(&[("Static", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.copy_timestamps {
        req_builder = req_builder.query(&[("CopyTimestamps", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("StartTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.width {
        req_builder = req_builder.query(&[("Width", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.height {
        req_builder = req_builder.query(&[("Height", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_width {
        req_builder = req_builder.query(&[("MaxWidth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_height {
        req_builder = req_builder.query(&[("MaxHeight", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_bit_rate {
        req_builder = req_builder.query(&[("VideoBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_stream_index {
        req_builder = req_builder.query(&[("SubtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.subtitle_method {
        req_builder = req_builder.query(&[("SubtitleMethod", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_video_bit_depth {
        req_builder = req_builder.query(&[("MaxVideoBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_codec {
        req_builder = req_builder.query(&[("VideoCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_stream_index {
        req_builder = req_builder.query(&[("AudioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.video_stream_index {
        req_builder = req_builder.query(&[("VideoStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("api_key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<HeadVideosByIdStreamByContainerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

