/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsPostbackAction {
    #[serde(rename = "TargetEditorId", skip_serializing_if = "Option::is_none")]
    pub target_editor_id: Option<String>,
    #[serde(rename = "PostbackCommandId", skip_serializing_if = "Option::is_none")]
    pub postback_command_id: Option<String>,
    #[serde(rename = "CommandParameterPropertyId", skip_serializing_if = "Option::is_none")]
    pub command_parameter_property_id: Option<String>,
}

impl ActionsPostbackAction {
    pub fn new() -> ActionsPostbackAction {
        ActionsPostbackAction {
            target_editor_id: None,
            postback_command_id: None,
            command_parameter_property_id: None,
        }
    }
}

