/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiConfigurationPageInfo {
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "EnableInMainMenu", skip_serializing_if = "Option::is_none")]
    pub enable_in_main_menu: Option<bool>,
    #[serde(rename = "EnableInUserMenu", skip_serializing_if = "Option::is_none")]
    pub enable_in_user_menu: Option<bool>,
    #[serde(rename = "FeatureId", skip_serializing_if = "Option::is_none")]
    pub feature_id: Option<String>,
    #[serde(rename = "MenuSection", skip_serializing_if = "Option::is_none")]
    pub menu_section: Option<String>,
    #[serde(rename = "MenuIcon", skip_serializing_if = "Option::is_none")]
    pub menu_icon: Option<String>,
    #[serde(rename = "DisplayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "ConfigurationPageType", skip_serializing_if = "Option::is_none")]
    pub configuration_page_type: Option<models::PluginsConfigurationPageType>,
    #[serde(rename = "PluginId", skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    #[serde(rename = "Href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "NavMenuId", skip_serializing_if = "Option::is_none")]
    pub nav_menu_id: Option<String>,
    #[serde(rename = "Plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Box<models::CommonPluginsIPlugin>>,
    #[serde(rename = "Translations", skip_serializing_if = "Option::is_none")]
    pub translations: Option<Vec<String>>,
}

impl ApiConfigurationPageInfo {
    pub fn new() -> ApiConfigurationPageInfo {
        ApiConfigurationPageInfo {
            name: None,
            enable_in_main_menu: None,
            enable_in_user_menu: None,
            feature_id: None,
            menu_section: None,
            menu_icon: None,
            display_name: None,
            configuration_page_type: None,
            plugin_id: None,
            href: None,
            nav_menu_id: None,
            plugin: None,
            translations: None,
        }
    }
}

