/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttributesSimpleCondition : Conditions on the source value.  
/// Conditions on the source value.  
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AttributesSimpleCondition {
    #[serde(rename = "IsTrue")]
    IsTrue,
    #[serde(rename = "IsFalse")]
    IsFalse,
    #[serde(rename = "IsNull")]
    IsNull,
    #[serde(rename = "IsNotNullOrEmpty")]
    IsNotNullOrEmpty,

}

impl std::fmt::Display for AttributesSimpleCondition {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::IsTrue => write!(f, "IsTrue"),
            Self::IsFalse => write!(f, "IsFalse"),
            Self::IsNull => write!(f, "IsNull"),
            Self::IsNotNullOrEmpty => write!(f, "IsNotNullOrEmpty"),
        }
    }
}

impl Default for AttributesSimpleCondition {
    fn default() -> AttributesSimpleCondition {
        Self::IsTrue
    }
}

