/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodecProfile {
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::CodecType>,
    #[serde(rename = "Conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<models::ProfileCondition>>,
    #[serde(rename = "ApplyConditions", skip_serializing_if = "Option::is_none")]
    pub apply_conditions: Option<Vec<models::ProfileCondition>>,
    #[serde(rename = "Codec", skip_serializing_if = "Option::is_none")]
    pub codec: Option<String>,
    #[serde(rename = "Container", skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
}

impl CodecProfile {
    pub fn new() -> CodecProfile {
        CodecProfile {
            r#type: None,
            conditions: None,
            apply_conditions: None,
            codec: None,
            container: None,
        }
    }
}

