/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodecConfiguration {
    /// A value indicating whether the codec is enabled.
    #[serde(rename = "IsEnabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// The selection priority for the codec.    Higher values mean higher priority.
    #[serde(rename = "Priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// The codec identifier.
    #[serde(rename = "CodecId", skip_serializing_if = "Option::is_none")]
    pub codec_id: Option<String>,
}

impl CodecConfiguration {
    pub fn new() -> CodecConfiguration {
        CodecConfiguration {
            is_enabled: None,
            priority: None,
            codec_id: None,
        }
    }
}

