/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodecDirections : Enum for indicating the processing direction of a codec.  
/// Enum for indicating the processing direction of a codec.  
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CodecDirections {
    #[serde(rename = "Encoder")]
    Encoder,
    #[serde(rename = "Decoder")]
    Decoder,

}

impl std::fmt::Display for CodecDirections {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Encoder => write!(f, "Encoder"),
            Self::Decoder => write!(f, "Decoder"),
        }
    }
}

impl Default for CodecDirections {
    fn default() -> CodecDirections {
        Self::Encoder
    }
}

