/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectUserLinkType {
    #[serde(rename = "LinkedUser")]
    LinkedUser,
    #[serde(rename = "Guest")]
    Guest,

}

impl std::fmt::Display for ConnectUserLinkType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LinkedUser => write!(f, "LinkedUser"),
            Self::Guest => write!(f, "Guest"),
        }
    }
}

impl Default for ConnectUserLinkType {
    fn default() -> ConnectUserLinkType {
        Self::LinkedUser
    }
}

