/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DlnaProfilesProtocolInfoDetection {
    #[serde(rename = "EnabledForVideo", skip_serializing_if = "Option::is_none")]
    pub enabled_for_video: Option<bool>,
    #[serde(rename = "EnabledForAudio", skip_serializing_if = "Option::is_none")]
    pub enabled_for_audio: Option<bool>,
    #[serde(rename = "EnabledForPhotos", skip_serializing_if = "Option::is_none")]
    pub enabled_for_photos: Option<bool>,
}

impl DlnaProfilesProtocolInfoDetection {
    pub fn new() -> DlnaProfilesProtocolInfoDetection {
        DlnaProfilesProtocolInfoDetection {
            enabled_for_video: None,
            enabled_for_audio: None,
            enabled_for_photos: None,
        }
    }
}

