/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntitiesUser : Class User  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntitiesUser {
    /// From now on all user paths will be Id\\-based. This is for backwards compatibility.
    #[serde(rename = "UsesIdForConfigurationPath", skip_serializing_if = "Option::is_none")]
    pub uses_id_for_configuration_path: Option<bool>,
    /// The password.
    #[serde(rename = "Password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "EasyPassword", skip_serializing_if = "Option::is_none")]
    pub easy_password: Option<String>,
    #[serde(rename = "Salt", skip_serializing_if = "Option::is_none")]
    pub salt: Option<String>,
    #[serde(rename = "ConnectUserName", skip_serializing_if = "Option::is_none")]
    pub connect_user_name: Option<String>,
    #[serde(rename = "ConnectUserId", skip_serializing_if = "Option::is_none")]
    pub connect_user_id: Option<String>,
    #[serde(rename = "ConnectLinkType", skip_serializing_if = "Option::is_none")]
    pub connect_link_type: Option<models::ConnectUserLinkType>,
    #[serde(rename = "ConnectAccessKey", skip_serializing_if = "Option::is_none")]
    pub connect_access_key: Option<String>,
    #[serde(rename = "ImageInfos", skip_serializing_if = "Option::is_none")]
    pub image_infos: Option<Vec<models::EntitiesItemImageInfo>>,
    /// The name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The last login date.
    #[serde(rename = "LastLoginDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_login_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The last activity date.
    #[serde(rename = "LastActivityDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_activity_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "PlayedPercentage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub played_percentage: Option<Option<f64>>,
    #[serde(rename = "RecursiveChildCountEqualsChildCount", skip_serializing_if = "Option::is_none")]
    pub recursive_child_count_equals_child_count: Option<bool>,
    /// Internal use only
    #[serde(rename = "OriginalParsedName", skip_serializing_if = "Option::is_none")]
    pub original_parsed_name: Option<String>,
    /// Internal use only
    #[serde(rename = "IsNameParsedFromFolder", skip_serializing_if = "Option::is_none")]
    pub is_name_parsed_from_folder: Option<bool>,
    #[serde(rename = "IdString", skip_serializing_if = "Option::is_none")]
    pub id_string: Option<String>,
    /// The date created.
    #[serde(rename = "DateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ImportedCollections", skip_serializing_if = "Option::is_none")]
    pub imported_collections: Option<Vec<models::LinkedItemInfo>>,
    #[serde(rename = "ResolvedPresentationUniqueKey", skip_serializing_if = "Option::is_none")]
    pub resolved_presentation_unique_key: Option<String>,
}

impl EntitiesUser {
    /// Class User  
    pub fn new() -> EntitiesUser {
        EntitiesUser {
            uses_id_for_configuration_path: None,
            password: None,
            easy_password: None,
            salt: None,
            connect_user_name: None,
            connect_user_id: None,
            connect_link_type: None,
            connect_access_key: None,
            image_infos: None,
            name: None,
            last_login_date: None,
            last_activity_date: None,
            played_percentage: None,
            recursive_child_count_equals_child_count: None,
            original_parsed_name: None,
            is_name_parsed_from_folder: None,
            id_string: None,
            date_created: None,
            imported_collections: None,
            resolved_presentation_unique_key: None,
        }
    }
}

