/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalIdInfo {
    /// The name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The key.
    #[serde(rename = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "Website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// The URL format string.
    #[serde(rename = "UrlFormatString", skip_serializing_if = "Option::is_none")]
    pub url_format_string: Option<String>,
    #[serde(rename = "IsSupportedAsIdentifier", skip_serializing_if = "Option::is_none")]
    pub is_supported_as_identifier: Option<bool>,
}

impl ExternalIdInfo {
    pub fn new() -> ExternalIdInfo {
        ExternalIdInfo {
            name: None,
            key: None,
            website: None,
            url_format_string: None,
            is_supported_as_identifier: None,
        }
    }
}

