/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GlobalizationCountryInfo : Class CountryInfo  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalizationCountryInfo {
    /// The name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The display name.
    #[serde(rename = "DisplayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The English name.
    #[serde(rename = "EnglishName", skip_serializing_if = "Option::is_none")]
    pub english_name: Option<String>,
    /// The name of the two letter ISO region.
    #[serde(rename = "TwoLetterISORegionName", skip_serializing_if = "Option::is_none")]
    pub two_letter_iso_region_name: Option<String>,
    /// The name of the three letter ISO region.
    #[serde(rename = "ThreeLetterISORegionName", skip_serializing_if = "Option::is_none")]
    pub three_letter_iso_region_name: Option<String>,
}

impl GlobalizationCountryInfo {
    /// Class CountryInfo  
    pub fn new() -> GlobalizationCountryInfo {
        GlobalizationCountryInfo {
            name: None,
            display_name: None,
            english_name: None,
            two_letter_iso_region_name: None,
            three_letter_iso_region_name: None,
        }
    }
}

