/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageSavingConvention {
    #[serde(rename = "Legacy")]
    Legacy,
    #[serde(rename = "Compatible")]
    Compatible,

}

impl std::fmt::Display for ImageSavingConvention {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Legacy => write!(f, "Legacy"),
            Self::Compatible => write!(f, "Compatible"),
        }
    }
}

impl Default for ImageSavingConvention {
    fn default() -> ImageSavingConvention {
        Self::Legacy
    }
}

