/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageProviderInfo : Class ImageProviderInfo.  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageProviderInfo {
    /// The name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "SupportedImages", skip_serializing_if = "Option::is_none")]
    pub supported_images: Option<Vec<models::ImageType>>,
}

impl ImageProviderInfo {
    /// Class ImageProviderInfo.  
    pub fn new() -> ImageProviderInfo {
        ImageProviderInfo {
            name: None,
            supported_images: None,
        }
    }
}

