/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageOption {
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ImageType>,
    /// The limit.
    #[serde(rename = "Limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// The minimum width.
    #[serde(rename = "MinWidth", skip_serializing_if = "Option::is_none")]
    pub min_width: Option<i32>,
}

impl ImageOption {
    pub fn new() -> ImageOption {
        ImageOption {
            r#type: None,
            limit: None,
            min_width: None,
        }
    }
}

