/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemCounts : Class LibrarySummary  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemCounts {
    /// The movie count.
    #[serde(rename = "MovieCount", skip_serializing_if = "Option::is_none")]
    pub movie_count: Option<i32>,
    /// The series count.
    #[serde(rename = "SeriesCount", skip_serializing_if = "Option::is_none")]
    pub series_count: Option<i32>,
    /// The episode count.
    #[serde(rename = "EpisodeCount", skip_serializing_if = "Option::is_none")]
    pub episode_count: Option<i32>,
    /// The game count.
    #[serde(rename = "GameCount", skip_serializing_if = "Option::is_none")]
    pub game_count: Option<i32>,
    #[serde(rename = "ArtistCount", skip_serializing_if = "Option::is_none")]
    pub artist_count: Option<i32>,
    #[serde(rename = "ProgramCount", skip_serializing_if = "Option::is_none")]
    pub program_count: Option<i32>,
    /// The game system count.
    #[serde(rename = "GameSystemCount", skip_serializing_if = "Option::is_none")]
    pub game_system_count: Option<i32>,
    /// The trailer count.
    #[serde(rename = "TrailerCount", skip_serializing_if = "Option::is_none")]
    pub trailer_count: Option<i32>,
    /// The song count.
    #[serde(rename = "SongCount", skip_serializing_if = "Option::is_none")]
    pub song_count: Option<i32>,
    /// The album count.
    #[serde(rename = "AlbumCount", skip_serializing_if = "Option::is_none")]
    pub album_count: Option<i32>,
    /// The music video count.
    #[serde(rename = "MusicVideoCount", skip_serializing_if = "Option::is_none")]
    pub music_video_count: Option<i32>,
    /// The box set count.
    #[serde(rename = "BoxSetCount", skip_serializing_if = "Option::is_none")]
    pub box_set_count: Option<i32>,
    /// The book count.
    #[serde(rename = "BookCount", skip_serializing_if = "Option::is_none")]
    pub book_count: Option<i32>,
    #[serde(rename = "ItemCount", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
}

impl ItemCounts {
    /// Class LibrarySummary  
    pub fn new() -> ItemCounts {
        ItemCounts {
            movie_count: None,
            series_count: None,
            episode_count: None,
            game_count: None,
            artist_count: None,
            program_count: None,
            game_system_count: None,
            trailer_count: None,
            song_count: None,
            album_count: None,
            music_video_count: None,
            box_set_count: None,
            book_count: None,
            item_count: None,
        }
    }
}

