/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryRenameVirtualFolder {
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "NewName", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
}

impl LibraryRenameVirtualFolder {
    pub fn new() -> LibraryRenameVirtualFolder {
        LibraryRenameVirtualFolder {
            id: None,
            new_name: None,
        }
    }
}

