/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LibraryRemoveMediaPath {
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "Path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "RefreshLibrary", skip_serializing_if = "Option::is_none")]
    pub refresh_library: Option<bool>,
}

impl LibraryRemoveMediaPath {
    pub fn new() -> LibraryRemoveMediaPath {
        LibraryRemoveMediaPath {
            id: None,
            path: None,
            refresh_library: None,
        }
    }
}

