/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveTvKeywordInfo {
    #[serde(rename = "KeywordType", skip_serializing_if = "Option::is_none")]
    pub keyword_type: Option<models::LiveTvKeywordType>,
    #[serde(rename = "Keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<String>,
}

impl LiveTvKeywordInfo {
    pub fn new() -> LiveTvKeywordInfo {
        LiveTvKeywordInfo {
            keyword_type: None,
            keyword: None,
        }
    }
}

