/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveTvLiveTvInfo {
    /// A value indicating whether this instance is enabled.
    #[serde(rename = "IsEnabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// The enabled users.
    #[serde(rename = "EnabledUsers", skip_serializing_if = "Option::is_none")]
    pub enabled_users: Option<Vec<String>>,
}

impl LiveTvLiveTvInfo {
    pub fn new() -> LiveTvLiveTvInfo {
        LiveTvLiveTvInfo {
            is_enabled: None,
            enabled_users: None,
        }
    }
}

