/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveStreamRequest {
    #[serde(rename = "OpenToken", skip_serializing_if = "Option::is_none")]
    pub open_token: Option<String>,
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "PlaySessionId", skip_serializing_if = "Option::is_none")]
    pub play_session_id: Option<String>,
    #[serde(rename = "MaxStreamingBitrate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_streaming_bitrate: Option<Option<i64>>,
    #[serde(rename = "StartTimeTicks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_time_ticks: Option<Option<i64>>,
    #[serde(rename = "AudioStreamIndex", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub audio_stream_index: Option<Option<i32>>,
    #[serde(rename = "SubtitleStreamIndex", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subtitle_stream_index: Option<Option<i32>>,
    #[serde(rename = "MaxAudioChannels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_audio_channels: Option<Option<i32>>,
    #[serde(rename = "ItemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    #[serde(rename = "DeviceProfile", skip_serializing_if = "Option::is_none")]
    pub device_profile: Option<Box<models::DeviceProfile>>,
    #[serde(rename = "EnableDirectPlay", skip_serializing_if = "Option::is_none")]
    pub enable_direct_play: Option<bool>,
    #[serde(rename = "EnableDirectStream", skip_serializing_if = "Option::is_none")]
    pub enable_direct_stream: Option<bool>,
    #[serde(rename = "EnableTranscoding", skip_serializing_if = "Option::is_none")]
    pub enable_transcoding: Option<bool>,
    #[serde(rename = "AllowVideoStreamCopy", skip_serializing_if = "Option::is_none")]
    pub allow_video_stream_copy: Option<bool>,
    #[serde(rename = "AllowInterlacedVideoStreamCopy", skip_serializing_if = "Option::is_none")]
    pub allow_interlaced_video_stream_copy: Option<bool>,
    #[serde(rename = "AllowAudioStreamCopy", skip_serializing_if = "Option::is_none")]
    pub allow_audio_stream_copy: Option<bool>,
}

impl LiveStreamRequest {
    pub fn new() -> LiveStreamRequest {
        LiveStreamRequest {
            open_token: None,
            user_id: None,
            play_session_id: None,
            max_streaming_bitrate: None,
            start_time_ticks: None,
            audio_stream_index: None,
            subtitle_stream_index: None,
            max_audio_channels: None,
            item_id: None,
            device_profile: None,
            enable_direct_play: None,
            enable_direct_stream: None,
            enable_transcoding: None,
            allow_video_stream_copy: None,
            allow_interlaced_video_stream_copy: None,
            allow_audio_stream_copy: None,
        }
    }
}

