/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveTvTimerInfoDto {
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::LiveTvRecordingStatus>,
    /// The series timer identifier.
    #[serde(rename = "SeriesTimerId", skip_serializing_if = "Option::is_none")]
    pub series_timer_id: Option<String>,
    /// The run time ticks.
    #[serde(rename = "RunTimeTicks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub run_time_ticks: Option<Option<i64>>,
    #[serde(rename = "ProgramInfo", skip_serializing_if = "Option::is_none")]
    pub program_info: Option<Box<models::BaseItemDto>>,
    #[serde(rename = "TimerType", skip_serializing_if = "Option::is_none")]
    pub timer_type: Option<models::LiveTvTimerType>,
    /// Id of the recording.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The server identifier.
    #[serde(rename = "ServerId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    /// ChannelId of the recording.
    #[serde(rename = "ChannelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    /// ChannelName of the recording.
    #[serde(rename = "ChannelName", skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    #[serde(rename = "ChannelNumber", skip_serializing_if = "Option::is_none")]
    pub channel_number: Option<String>,
    #[serde(rename = "ChannelPrimaryImageTag", skip_serializing_if = "Option::is_none")]
    pub channel_primary_image_tag: Option<String>,
    /// The program identifier.
    #[serde(rename = "ProgramId", skip_serializing_if = "Option::is_none")]
    pub program_id: Option<String>,
    /// Name of the recording.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of the recording.
    #[serde(rename = "Overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "ParentFolderId", skip_serializing_if = "Option::is_none")]
    pub parent_folder_id: Option<String>,
    /// The start date of the recording, in UTC.
    #[serde(rename = "StartDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The end date of the recording, in UTC.
    #[serde(rename = "EndDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The priority.
    #[serde(rename = "Priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// The pre padding seconds.
    #[serde(rename = "PrePaddingSeconds", skip_serializing_if = "Option::is_none")]
    pub pre_padding_seconds: Option<i32>,
    /// The post padding seconds.
    #[serde(rename = "PostPaddingSeconds", skip_serializing_if = "Option::is_none")]
    pub post_padding_seconds: Option<i32>,
    /// A value indicating whether this instance is pre padding required.
    #[serde(rename = "IsPrePaddingRequired", skip_serializing_if = "Option::is_none")]
    pub is_pre_padding_required: Option<bool>,
    /// If the item does not have any backdrops, this will hold the Id of the Parent that has one.
    #[serde(rename = "ParentBackdropItemId", skip_serializing_if = "Option::is_none")]
    pub parent_backdrop_item_id: Option<String>,
    /// The parent backdrop image tags.
    #[serde(rename = "ParentBackdropImageTags", skip_serializing_if = "Option::is_none")]
    pub parent_backdrop_image_tags: Option<Vec<String>>,
    /// A value indicating whether this instance is post padding required.
    #[serde(rename = "IsPostPaddingRequired", skip_serializing_if = "Option::is_none")]
    pub is_post_padding_required: Option<bool>,
    #[serde(rename = "KeepUntil", skip_serializing_if = "Option::is_none")]
    pub keep_until: Option<models::LiveTvKeepUntil>,
}

impl LiveTvTimerInfoDto {
    pub fn new() -> LiveTvTimerInfoDto {
        LiveTvTimerInfoDto {
            status: None,
            series_timer_id: None,
            run_time_ticks: None,
            program_info: None,
            timer_type: None,
            id: None,
            r#type: None,
            server_id: None,
            channel_id: None,
            channel_name: None,
            channel_number: None,
            channel_primary_image_tag: None,
            program_id: None,
            name: None,
            overview: None,
            parent_folder_id: None,
            start_date: None,
            end_date: None,
            priority: None,
            pre_padding_seconds: None,
            post_padding_seconds: None,
            is_pre_padding_required: None,
            parent_backdrop_item_id: None,
            parent_backdrop_image_tags: None,
            is_post_padding_required: None,
            keep_until: None,
        }
    }
}

