/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MbBackupApiDataRestoreOptions {
    #[serde(rename = "Users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::MbBackupApiUserRestoreInfo>>,
}

impl MbBackupApiDataRestoreOptions {
    pub fn new() -> MbBackupApiDataRestoreOptions {
        MbBackupApiDataRestoreOptions {
            users: None,
        }
    }
}

