/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MbBackupApiRestoreOptions {
    #[serde(rename = "RestoreServerId", skip_serializing_if = "Option::is_none")]
    pub restore_server_id: Option<bool>,
    #[serde(rename = "UseFiles", skip_serializing_if = "Option::is_none")]
    pub use_files: Option<String>,
}

impl MbBackupApiRestoreOptions {
    pub fn new() -> MbBackupApiRestoreOptions {
        MbBackupApiRestoreOptions {
            restore_server_id: None,
            use_files: None,
        }
    }
}

