/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataEditorInfo {
    #[serde(rename = "ParentalRatingOptions", skip_serializing_if = "Option::is_none")]
    pub parental_rating_options: Option<Vec<models::ParentalRating>>,
    #[serde(rename = "Countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<Vec<models::GlobalizationCountryInfo>>,
    #[serde(rename = "Cultures", skip_serializing_if = "Option::is_none")]
    pub cultures: Option<Vec<models::GlobalizationCultureDto>>,
    #[serde(rename = "ExternalIdInfos", skip_serializing_if = "Option::is_none")]
    pub external_id_infos: Option<Vec<models::ExternalIdInfo>>,
    #[serde(rename = "PersonExternalIdInfos", skip_serializing_if = "Option::is_none")]
    pub person_external_id_infos: Option<Vec<models::ExternalIdInfo>>,
}

impl MetadataEditorInfo {
    pub fn new() -> MetadataEditorInfo {
        MetadataEditorInfo {
            parental_rating_options: None,
            countries: None,
            cultures: None,
            external_id_infos: None,
            person_external_id_infos: None,
        }
    }
}

