/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NetSocketsAddressFamily {
    #[serde(rename = "Unspecified")]
    Unspecified,
    #[serde(rename = "Unix")]
    Unix,
    #[serde(rename = "InterNetwork")]
    InterNetwork,
    #[serde(rename = "ImpLink")]
    ImpLink,
    #[serde(rename = "Pup")]
    Pup,
    #[serde(rename = "Chaos")]
    Chaos,
    #[serde(rename = "NS")]
    Ns,
    #[serde(rename = "Ipx")]
    Ipx,
    #[serde(rename = "Iso")]
    Iso,
    #[serde(rename = "Osi")]
    Osi,
    #[serde(rename = "Ecma")]
    Ecma,
    #[serde(rename = "DataKit")]
    DataKit,
    #[serde(rename = "Ccitt")]
    Ccitt,
    #[serde(rename = "Sna")]
    Sna,
    #[serde(rename = "DecNet")]
    DecNet,
    #[serde(rename = "DataLink")]
    DataLink,
    #[serde(rename = "Lat")]
    Lat,
    #[serde(rename = "HyperChannel")]
    HyperChannel,
    #[serde(rename = "AppleTalk")]
    AppleTalk,
    #[serde(rename = "NetBios")]
    NetBios,
    #[serde(rename = "VoiceView")]
    VoiceView,
    #[serde(rename = "FireFox")]
    FireFox,
    #[serde(rename = "Banyan")]
    Banyan,
    #[serde(rename = "Atm")]
    Atm,
    #[serde(rename = "InterNetworkV6")]
    InterNetworkV6,
    #[serde(rename = "Cluster")]
    Cluster,
    #[serde(rename = "Ieee12844")]
    Ieee12844,
    #[serde(rename = "Irda")]
    Irda,
    #[serde(rename = "NetworkDesigners")]
    NetworkDesigners,
    #[serde(rename = "Max")]
    Max,
    #[serde(rename = "Packet")]
    Packet,
    #[serde(rename = "ControllerAreaNetwork")]
    ControllerAreaNetwork,
    #[serde(rename = "Unknown")]
    Unknown,

}

impl std::fmt::Display for NetSocketsAddressFamily {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unspecified => write!(f, "Unspecified"),
            Self::Unix => write!(f, "Unix"),
            Self::InterNetwork => write!(f, "InterNetwork"),
            Self::ImpLink => write!(f, "ImpLink"),
            Self::Pup => write!(f, "Pup"),
            Self::Chaos => write!(f, "Chaos"),
            Self::Ns => write!(f, "NS"),
            Self::Ipx => write!(f, "Ipx"),
            Self::Iso => write!(f, "Iso"),
            Self::Osi => write!(f, "Osi"),
            Self::Ecma => write!(f, "Ecma"),
            Self::DataKit => write!(f, "DataKit"),
            Self::Ccitt => write!(f, "Ccitt"),
            Self::Sna => write!(f, "Sna"),
            Self::DecNet => write!(f, "DecNet"),
            Self::DataLink => write!(f, "DataLink"),
            Self::Lat => write!(f, "Lat"),
            Self::HyperChannel => write!(f, "HyperChannel"),
            Self::AppleTalk => write!(f, "AppleTalk"),
            Self::NetBios => write!(f, "NetBios"),
            Self::VoiceView => write!(f, "VoiceView"),
            Self::FireFox => write!(f, "FireFox"),
            Self::Banyan => write!(f, "Banyan"),
            Self::Atm => write!(f, "Atm"),
            Self::InterNetworkV6 => write!(f, "InterNetworkV6"),
            Self::Cluster => write!(f, "Cluster"),
            Self::Ieee12844 => write!(f, "Ieee12844"),
            Self::Irda => write!(f, "Irda"),
            Self::NetworkDesigners => write!(f, "NetworkDesigners"),
            Self::Max => write!(f, "Max"),
            Self::Packet => write!(f, "Packet"),
            Self::ControllerAreaNetwork => write!(f, "ControllerAreaNetwork"),
            Self::Unknown => write!(f, "Unknown"),
        }
    }
}

impl Default for NetSocketsAddressFamily {
    fn default() -> NetSocketsAddressFamily {
        Self::Unspecified
    }
}

