/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessRunMetricsProcessMetricPoint {
    /// The time.
    #[serde(rename = "Time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// The cpu percent.
    #[serde(rename = "CpuPercent", skip_serializing_if = "Option::is_none")]
    pub cpu_percent: Option<f64>,
    /// The virtual memory.
    #[serde(rename = "VirtualMemory", skip_serializing_if = "Option::is_none")]
    pub virtual_memory: Option<f64>,
    /// The working set.
    #[serde(rename = "WorkingSet", skip_serializing_if = "Option::is_none")]
    pub working_set: Option<f64>,
}

impl ProcessRunMetricsProcessMetricPoint {
    pub fn new() -> ProcessRunMetricsProcessMetricPoint {
        ProcessRunMetricsProcessMetricPoint {
            time: None,
            cpu_percent: None,
            virtual_memory: None,
            working_set: None,
        }
    }
}

