/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileInformation : Class for unified presentation of all information associated with a specific codec profile.  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileInformation {
    /// The enum member name of the profile.
    #[serde(rename = "ShortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    /// The common name of the profile.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Detail information about the profile.
    #[serde(rename = "Details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// A unique identifier.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The bit depths.
    #[serde(rename = "BitDepths", skip_serializing_if = "Option::is_none")]
    pub bit_depths: Option<Vec<i32>>,
}

impl ProfileInformation {
    /// Class for unified presentation of all information associated with a specific codec profile.  
    pub fn new() -> ProfileInformation {
        ProfileInformation {
            short_name: None,
            description: None,
            details: None,
            id: None,
            bit_depths: None,
        }
    }
}

