/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileLevelInformation : A class combining both `Emby.Media.Model.Types.ProfileInformation` and `Emby.Media.Model.Types.LevelInformation`.  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileLevelInformation {
    #[serde(rename = "Profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<Box<models::ProfileInformation>>,
    #[serde(rename = "Level", skip_serializing_if = "Option::is_none")]
    pub level: Option<Box<models::LevelInformation>>,
}

impl ProfileLevelInformation {
    /// A class combining both `Emby.Media.Model.Types.ProfileInformation` and `Emby.Media.Model.Types.LevelInformation`.  
    pub fn new() -> ProfileLevelInformation {
        ProfileLevelInformation {
            profile: None,
            level: None,
        }
    }
}

