/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RatingType {
    #[serde(rename = "Score")]
    Score,
    #[serde(rename = "Likes")]
    Likes,

}

impl std::fmt::Display for RatingType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Score => write!(f, "Score"),
            Self::Likes => write!(f, "Likes"),
        }
    }
}

impl Default for RatingType {
    fn default() -> RatingType {
        Self::Score
    }
}

