/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecommendationType {
    #[serde(rename = "SimilarToRecentlyPlayed")]
    SimilarToRecentlyPlayed,
    #[serde(rename = "SimilarToLikedItem")]
    SimilarToLikedItem,
    #[serde(rename = "HasDirectorFromRecentlyPlayed")]
    HasDirectorFromRecentlyPlayed,
    #[serde(rename = "HasActorFromRecentlyPlayed")]
    HasActorFromRecentlyPlayed,
    #[serde(rename = "HasLikedDirector")]
    HasLikedDirector,
    #[serde(rename = "HasLikedActor")]
    HasLikedActor,

}

impl std::fmt::Display for RecommendationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SimilarToRecentlyPlayed => write!(f, "SimilarToRecentlyPlayed"),
            Self::SimilarToLikedItem => write!(f, "SimilarToLikedItem"),
            Self::HasDirectorFromRecentlyPlayed => write!(f, "HasDirectorFromRecentlyPlayed"),
            Self::HasActorFromRecentlyPlayed => write!(f, "HasActorFromRecentlyPlayed"),
            Self::HasLikedDirector => write!(f, "HasLikedDirector"),
            Self::HasLikedActor => write!(f, "HasLikedActor"),
        }
    }
}

impl Default for RecommendationType {
    fn default() -> RecommendationType {
        Self::SimilarToRecentlyPlayed
    }
}

