/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoteImageInfo : Class RemoteImageInfo  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteImageInfo {
    /// The name of the provider.
    #[serde(rename = "ProviderName", skip_serializing_if = "Option::is_none")]
    pub provider_name: Option<String>,
    /// The URL.
    #[serde(rename = "Url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// A url used for previewing a smaller version
    #[serde(rename = "ThumbnailUrl", skip_serializing_if = "Option::is_none")]
    pub thumbnail_url: Option<String>,
    /// The height.
    #[serde(rename = "Height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    /// The width.
    #[serde(rename = "Width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<i32>>,
    /// The community rating.
    #[serde(rename = "CommunityRating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub community_rating: Option<Option<f64>>,
    /// The vote count.
    #[serde(rename = "VoteCount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<Option<i32>>,
    /// The language.
    #[serde(rename = "Language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "DisplayLanguage", skip_serializing_if = "Option::is_none")]
    pub display_language: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ImageType>,
    #[serde(rename = "RatingType", skip_serializing_if = "Option::is_none")]
    pub rating_type: Option<models::RatingType>,
}

impl RemoteImageInfo {
    /// Class RemoteImageInfo  
    pub fn new() -> RemoteImageInfo {
        RemoteImageInfo {
            provider_name: None,
            url: None,
            thumbnail_url: None,
            height: None,
            width: None,
            community_rating: None,
            vote_count: None,
            language: None,
            display_language: None,
            r#type: None,
            rating_type: None,
        }
    }
}

