/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteSearchQueryArtistInfo {
    #[serde(rename = "SearchInfo", skip_serializing_if = "Option::is_none")]
    pub search_info: Option<Box<models::ArtistInfo>>,
    #[serde(rename = "ItemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    #[serde(rename = "SearchProviderName", skip_serializing_if = "Option::is_none")]
    pub search_provider_name: Option<String>,
    #[serde(rename = "Providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<Vec<String>>,
    #[serde(rename = "IncludeDisabledProviders", skip_serializing_if = "Option::is_none")]
    pub include_disabled_providers: Option<bool>,
}

impl RemoteSearchQueryArtistInfo {
    pub fn new() -> RemoteSearchQueryArtistInfo {
        RemoteSearchQueryArtistInfo {
            search_info: None,
            item_id: None,
            search_provider_name: None,
            providers: None,
            include_disabled_providers: None,
        }
    }
}

