/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerConfiguration : Represents the server configuration.  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerConfiguration {
    /// A value indicating whether \\[enable u pn p\\].
    #[serde(rename = "EnableUPnP", skip_serializing_if = "Option::is_none")]
    pub enable_upn_p: Option<bool>,
    /// The public mapped port.
    #[serde(rename = "PublicPort", skip_serializing_if = "Option::is_none")]
    pub public_port: Option<i32>,
    /// The public HTTPS port.
    #[serde(rename = "PublicHttpsPort", skip_serializing_if = "Option::is_none")]
    pub public_https_port: Option<i32>,
    /// The HTTP server port number.
    #[serde(rename = "HttpServerPortNumber", skip_serializing_if = "Option::is_none")]
    pub http_server_port_number: Option<i32>,
    /// The HTTPS server port number.
    #[serde(rename = "HttpsPortNumber", skip_serializing_if = "Option::is_none")]
    pub https_port_number: Option<i32>,
    /// A value indicating whether \\[use HTTPS\\].
    #[serde(rename = "EnableHttps", skip_serializing_if = "Option::is_none")]
    pub enable_https: Option<bool>,
    /// The value pointing to the file system where the ssl certiifcate is located..
    #[serde(rename = "CertificatePath", skip_serializing_if = "Option::is_none")]
    pub certificate_path: Option<String>,
    #[serde(rename = "CertificatePassword", skip_serializing_if = "Option::is_none")]
    pub certificate_password: Option<String>,
    /// A value indicating whether this instance is port authorized.
    #[serde(rename = "IsPortAuthorized", skip_serializing_if = "Option::is_none")]
    pub is_port_authorized: Option<bool>,
    #[serde(rename = "AutoRunWebApp", skip_serializing_if = "Option::is_none")]
    pub auto_run_web_app: Option<bool>,
    #[serde(rename = "EnableRemoteAccess", skip_serializing_if = "Option::is_none")]
    pub enable_remote_access: Option<bool>,
    #[serde(rename = "LogAllQueryTimes", skip_serializing_if = "Option::is_none")]
    pub log_all_query_times: Option<bool>,
    #[serde(rename = "DisableOutgoingIPv6", skip_serializing_if = "Option::is_none")]
    pub disable_outgoing_ipv6: Option<bool>,
    /// A value indicating whether \\[enable case sensitive item ids\\].
    #[serde(rename = "EnableCaseSensitiveItemIds", skip_serializing_if = "Option::is_none")]
    pub enable_case_sensitive_item_ids: Option<bool>,
    /// The metadata path.
    #[serde(rename = "MetadataPath", skip_serializing_if = "Option::is_none")]
    pub metadata_path: Option<String>,
    #[serde(rename = "MetadataNetworkPath", skip_serializing_if = "Option::is_none")]
    pub metadata_network_path: Option<String>,
    /// The preferred metadata language.
    #[serde(rename = "PreferredMetadataLanguage", skip_serializing_if = "Option::is_none")]
    pub preferred_metadata_language: Option<String>,
    /// The metadata country code.
    #[serde(rename = "MetadataCountryCode", skip_serializing_if = "Option::is_none")]
    pub metadata_country_code: Option<String>,
    /// Words to be removed from strings to create a sort name
    #[serde(rename = "SortRemoveWords", skip_serializing_if = "Option::is_none")]
    pub sort_remove_words: Option<Vec<String>>,
    /// The delay in seconds that we will wait after a file system change to try and discover what has been added/removed Some delay is necessary with some items because their creation is not atomic.  It involves the creation of several different directories and files.
    #[serde(rename = "LibraryMonitorDelaySeconds", skip_serializing_if = "Option::is_none")]
    pub library_monitor_delay_seconds: Option<i32>,
    /// A value indicating whether \\[enable dashboard response caching\\]. Allows potential contributors without visual studio to modify production dashboard code and test changes.
    #[serde(rename = "EnableDashboardResponseCaching", skip_serializing_if = "Option::is_none")]
    pub enable_dashboard_response_caching: Option<bool>,
    /// Allows the dashboard to be served from a custom path.
    #[serde(rename = "DashboardSourcePath", skip_serializing_if = "Option::is_none")]
    pub dashboard_source_path: Option<String>,
    #[serde(rename = "ImageSavingConvention", skip_serializing_if = "Option::is_none")]
    pub image_saving_convention: Option<models::ImageSavingConvention>,
    #[serde(rename = "EnableAutomaticRestart", skip_serializing_if = "Option::is_none")]
    pub enable_automatic_restart: Option<bool>,
    #[serde(rename = "ServerName", skip_serializing_if = "Option::is_none")]
    pub server_name: Option<String>,
    #[serde(rename = "PreferredDetectedRemoteAddressFamily", skip_serializing_if = "Option::is_none")]
    pub preferred_detected_remote_address_family: Option<models::NetSocketsAddressFamily>,
    #[serde(rename = "WanDdns", skip_serializing_if = "Option::is_none")]
    pub wan_ddns: Option<String>,
    #[serde(rename = "UICulture", skip_serializing_if = "Option::is_none")]
    pub ui_culture: Option<String>,
    #[serde(rename = "RemoteClientBitrateLimit", skip_serializing_if = "Option::is_none")]
    pub remote_client_bitrate_limit: Option<i32>,
    #[serde(rename = "LocalNetworkSubnets", skip_serializing_if = "Option::is_none")]
    pub local_network_subnets: Option<Vec<String>>,
    #[serde(rename = "LocalNetworkAddresses", skip_serializing_if = "Option::is_none")]
    pub local_network_addresses: Option<Vec<String>>,
    #[serde(rename = "EnableExternalContentInSuggestions", skip_serializing_if = "Option::is_none")]
    pub enable_external_content_in_suggestions: Option<bool>,
    #[serde(rename = "RequireHttps", skip_serializing_if = "Option::is_none")]
    pub require_https: Option<bool>,
    #[serde(rename = "IsBehindProxy", skip_serializing_if = "Option::is_none")]
    pub is_behind_proxy: Option<bool>,
    #[serde(rename = "RemoteIPFilter", skip_serializing_if = "Option::is_none")]
    pub remote_ip_filter: Option<Vec<String>>,
    #[serde(rename = "IsRemoteIPFilterBlacklist", skip_serializing_if = "Option::is_none")]
    pub is_remote_ip_filter_blacklist: Option<bool>,
    #[serde(rename = "ImageExtractionTimeoutMs", skip_serializing_if = "Option::is_none")]
    pub image_extraction_timeout_ms: Option<i32>,
    #[serde(rename = "PathSubstitutions", skip_serializing_if = "Option::is_none")]
    pub path_substitutions: Option<Vec<models::PathSubstitution>>,
    #[serde(rename = "UninstalledPlugins", skip_serializing_if = "Option::is_none")]
    pub uninstalled_plugins: Option<Vec<String>>,
    #[serde(rename = "CollapseVideoFolders", skip_serializing_if = "Option::is_none")]
    pub collapse_video_folders: Option<bool>,
    #[serde(rename = "EnableOriginalTrackTitles", skip_serializing_if = "Option::is_none")]
    pub enable_original_track_titles: Option<bool>,
    #[serde(rename = "VacuumDatabaseOnStartup", skip_serializing_if = "Option::is_none")]
    pub vacuum_database_on_startup: Option<bool>,
    #[serde(rename = "SimultaneousStreamLimit", skip_serializing_if = "Option::is_none")]
    pub simultaneous_stream_limit: Option<i32>,
    #[serde(rename = "DatabaseCacheSizeMB", skip_serializing_if = "Option::is_none")]
    pub database_cache_size_mb: Option<i32>,
    #[serde(rename = "EnableSqLiteMmio", skip_serializing_if = "Option::is_none")]
    pub enable_sq_lite_mmio: Option<bool>,
    #[serde(rename = "PlaylistsUpgradedToM3U", skip_serializing_if = "Option::is_none")]
    pub playlists_upgraded_to_m3_u: Option<bool>,
    #[serde(rename = "ImageExtractorUpgraded1", skip_serializing_if = "Option::is_none")]
    pub image_extractor_upgraded1: Option<bool>,
    #[serde(rename = "EnablePeopleLetterSubFolders", skip_serializing_if = "Option::is_none")]
    pub enable_people_letter_sub_folders: Option<bool>,
    #[serde(rename = "OptimizeDatabaseOnShutdown", skip_serializing_if = "Option::is_none")]
    pub optimize_database_on_shutdown: Option<bool>,
    #[serde(rename = "DatabaseAnalysisLimit", skip_serializing_if = "Option::is_none")]
    pub database_analysis_limit: Option<i32>,
    #[serde(rename = "MaxLibraryDatabaseConnections", skip_serializing_if = "Option::is_none")]
    pub max_library_database_connections: Option<i32>,
    #[serde(rename = "MaxAuthDbConnections", skip_serializing_if = "Option::is_none")]
    pub max_auth_db_connections: Option<i32>,
    #[serde(rename = "MaxOtherDbConnections", skip_serializing_if = "Option::is_none")]
    pub max_other_db_connections: Option<i32>,
    #[serde(rename = "DisableAsyncIO", skip_serializing_if = "Option::is_none")]
    pub disable_async_io: Option<bool>,
    #[serde(rename = "MigratedToUserItemShares8", skip_serializing_if = "Option::is_none")]
    pub migrated_to_user_item_shares8: Option<bool>,
    #[serde(rename = "MigratedLibraryOptionsToDb", skip_serializing_if = "Option::is_none")]
    pub migrated_library_options_to_db: Option<bool>,
    #[serde(rename = "AllowLegacyLocalNetworkPassword", skip_serializing_if = "Option::is_none")]
    pub allow_legacy_local_network_password: Option<bool>,
    #[serde(rename = "EnableSavedMetadataForPeople", skip_serializing_if = "Option::is_none")]
    pub enable_saved_metadata_for_people: Option<bool>,
    #[serde(rename = "TvChannelsRefreshed", skip_serializing_if = "Option::is_none")]
    pub tv_channels_refreshed: Option<bool>,
    #[serde(rename = "ProxyHeaderMode", skip_serializing_if = "Option::is_none")]
    pub proxy_header_mode: Option<models::ProxyHeaderMode>,
    #[serde(rename = "IsInMaintenanceMode", skip_serializing_if = "Option::is_none")]
    pub is_in_maintenance_mode: Option<bool>,
    #[serde(rename = "MaintenanceModeMessage", skip_serializing_if = "Option::is_none")]
    pub maintenance_mode_message: Option<String>,
    /// A value indicating whether \\[enable debug level logging\\].
    #[serde(rename = "EnableDebugLevelLogging", skip_serializing_if = "Option::is_none")]
    pub enable_debug_level_logging: Option<bool>,
    #[serde(rename = "RevertDebugLogging", skip_serializing_if = "Option::is_none")]
    pub revert_debug_logging: Option<String>,
    /// Enable automatically and silently updating of the application
    #[serde(rename = "EnableAutoUpdate", skip_serializing_if = "Option::is_none")]
    pub enable_auto_update: Option<bool>,
    /// The number of days we should retain log files
    #[serde(rename = "LogFileRetentionDays", skip_serializing_if = "Option::is_none")]
    pub log_file_retention_days: Option<i32>,
    /// A value indicating whether \\[run at startup\\].
    #[serde(rename = "RunAtStartup", skip_serializing_if = "Option::is_none")]
    pub run_at_startup: Option<bool>,
    /// A value indicating whether this instance is first run.
    #[serde(rename = "IsStartupWizardCompleted", skip_serializing_if = "Option::is_none")]
    pub is_startup_wizard_completed: Option<bool>,
    /// The cache path.
    #[serde(rename = "CachePath", skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
}

impl ServerConfiguration {
    /// Represents the server configuration.  
    pub fn new() -> ServerConfiguration {
        ServerConfiguration {
            enable_upn_p: None,
            public_port: None,
            public_https_port: None,
            http_server_port_number: None,
            https_port_number: None,
            enable_https: None,
            certificate_path: None,
            certificate_password: None,
            is_port_authorized: None,
            auto_run_web_app: None,
            enable_remote_access: None,
            log_all_query_times: None,
            disable_outgoing_ipv6: None,
            enable_case_sensitive_item_ids: None,
            metadata_path: None,
            metadata_network_path: None,
            preferred_metadata_language: None,
            metadata_country_code: None,
            sort_remove_words: None,
            library_monitor_delay_seconds: None,
            enable_dashboard_response_caching: None,
            dashboard_source_path: None,
            image_saving_convention: None,
            enable_automatic_restart: None,
            server_name: None,
            preferred_detected_remote_address_family: None,
            wan_ddns: None,
            ui_culture: None,
            remote_client_bitrate_limit: None,
            local_network_subnets: None,
            local_network_addresses: None,
            enable_external_content_in_suggestions: None,
            require_https: None,
            is_behind_proxy: None,
            remote_ip_filter: None,
            is_remote_ip_filter_blacklist: None,
            image_extraction_timeout_ms: None,
            path_substitutions: None,
            uninstalled_plugins: None,
            collapse_video_folders: None,
            enable_original_track_titles: None,
            vacuum_database_on_startup: None,
            simultaneous_stream_limit: None,
            database_cache_size_mb: None,
            enable_sq_lite_mmio: None,
            playlists_upgraded_to_m3_u: None,
            image_extractor_upgraded1: None,
            enable_people_letter_sub_folders: None,
            optimize_database_on_shutdown: None,
            database_analysis_limit: None,
            max_library_database_connections: None,
            max_auth_db_connections: None,
            max_other_db_connections: None,
            disable_async_io: None,
            migrated_to_user_item_shares8: None,
            migrated_library_options_to_db: None,
            allow_legacy_local_network_password: None,
            enable_saved_metadata_for_people: None,
            tv_channels_refreshed: None,
            proxy_header_mode: None,
            is_in_maintenance_mode: None,
            maintenance_mode_message: None,
            enable_debug_level_logging: None,
            revert_debug_logging: None,
            enable_auto_update: None,
            log_file_retention_days: None,
            run_at_startup: None,
            is_startup_wizard_completed: None,
            cache_path: None,
        }
    }
}

