/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionSessionInfo : Class SessionInfo  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionSessionInfo {
    #[serde(rename = "PlayState", skip_serializing_if = "Option::is_none")]
    pub play_state: Option<Box<models::PlayerStateInfo>>,
    #[serde(rename = "AdditionalUsers", skip_serializing_if = "Option::is_none")]
    pub additional_users: Option<Vec<models::SessionUserInfo>>,
    /// The remote end point.
    #[serde(rename = "RemoteEndPoint", skip_serializing_if = "Option::is_none")]
    pub remote_end_point: Option<String>,
    #[serde(rename = "Protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// The playable media types.
    #[serde(rename = "PlayableMediaTypes", skip_serializing_if = "Option::is_none")]
    pub playable_media_types: Option<Vec<String>>,
    #[serde(rename = "PlaylistItemId", skip_serializing_if = "Option::is_none")]
    pub playlist_item_id: Option<String>,
    #[serde(rename = "PlaylistIndex", skip_serializing_if = "Option::is_none")]
    pub playlist_index: Option<i32>,
    #[serde(rename = "PlaylistLength", skip_serializing_if = "Option::is_none")]
    pub playlist_length: Option<i32>,
    /// The id.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "ServerId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    /// The user id.
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "PartyId", skip_serializing_if = "Option::is_none")]
    pub party_id: Option<String>,
    /// The username.
    #[serde(rename = "UserName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "UserPrimaryImageTag", skip_serializing_if = "Option::is_none")]
    pub user_primary_image_tag: Option<String>,
    /// The type of the client.
    #[serde(rename = "Client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    /// The last activity date.
    #[serde(rename = "LastActivityDate", skip_serializing_if = "Option::is_none")]
    pub last_activity_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The name of the device.
    #[serde(rename = "DeviceName", skip_serializing_if = "Option::is_none")]
    pub device_name: Option<String>,
    #[serde(rename = "DeviceType", skip_serializing_if = "Option::is_none")]
    pub device_type: Option<String>,
    #[serde(rename = "NowPlayingItem", skip_serializing_if = "Option::is_none")]
    pub now_playing_item: Option<Box<models::BaseItemDto>>,
    #[serde(rename = "InternalDeviceId", skip_serializing_if = "Option::is_none")]
    pub internal_device_id: Option<i64>,
    /// The device id.
    #[serde(rename = "DeviceId", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    /// The application version.
    #[serde(rename = "ApplicationVersion", skip_serializing_if = "Option::is_none")]
    pub application_version: Option<String>,
    /// The application icon URL.
    #[serde(rename = "AppIconUrl", skip_serializing_if = "Option::is_none")]
    pub app_icon_url: Option<String>,
    /// The supported commands.
    #[serde(rename = "SupportedCommands", skip_serializing_if = "Option::is_none")]
    pub supported_commands: Option<Vec<String>>,
    #[serde(rename = "TranscodingInfo", skip_serializing_if = "Option::is_none")]
    pub transcoding_info: Option<Box<models::TranscodingInfo>>,
    #[serde(rename = "SupportsRemoteControl", skip_serializing_if = "Option::is_none")]
    pub supports_remote_control: Option<bool>,
}

impl SessionSessionInfo {
    /// Class SessionInfo  
    pub fn new() -> SessionSessionInfo {
        SessionSessionInfo {
            play_state: None,
            additional_users: None,
            remote_end_point: None,
            protocol: None,
            playable_media_types: None,
            playlist_item_id: None,
            playlist_index: None,
            playlist_length: None,
            id: None,
            server_id: None,
            user_id: None,
            party_id: None,
            user_name: None,
            user_primary_image_tag: None,
            client: None,
            last_activity_date: None,
            device_name: None,
            device_type: None,
            now_playing_item: None,
            internal_device_id: None,
            device_id: None,
            application_version: None,
            app_icon_url: None,
            supported_commands: None,
            transcoding_info: None,
            supports_remote_control: None,
        }
    }
}

