/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncJobOption {
    #[serde(rename = "Name")]
    Name,
    #[serde(rename = "Quality")]
    Quality,
    #[serde(rename = "UnwatchedOnly")]
    UnwatchedOnly,
    #[serde(rename = "SyncNewContent")]
    SyncNewContent,
    #[serde(rename = "ItemLimit")]
    ItemLimit,
    #[serde(rename = "Profile")]
    Profile,

}

impl std::fmt::Display for SyncJobOption {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Name => write!(f, "Name"),
            Self::Quality => write!(f, "Quality"),
            Self::UnwatchedOnly => write!(f, "UnwatchedOnly"),
            Self::SyncNewContent => write!(f, "SyncNewContent"),
            Self::ItemLimit => write!(f, "ItemLimit"),
            Self::Profile => write!(f, "Profile"),
        }
    }
}

impl Default for SyncJobOption {
    fn default() -> SyncJobOption {
        Self::Name
    }
}

