/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncDataRequest {
    #[serde(rename = "LocalItemIds", skip_serializing_if = "Option::is_none")]
    pub local_item_ids: Option<Vec<String>>,
    #[serde(rename = "InternalTargetIds", skip_serializing_if = "Option::is_none")]
    pub internal_target_ids: Option<Vec<i64>>,
}

impl SyncDataRequest {
    pub fn new() -> SyncDataRequest {
        SyncDataRequest {
            local_item_ids: None,
            internal_target_ids: None,
        }
    }
}

