/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncJobItemStatus {
    #[serde(rename = "Queued")]
    Queued,
    #[serde(rename = "Converting")]
    Converting,
    #[serde(rename = "ReadyToTransfer")]
    ReadyToTransfer,
    #[serde(rename = "Transferring")]
    Transferring,
    #[serde(rename = "Synced")]
    Synced,
    #[serde(rename = "Failed")]
    Failed,

}

impl std::fmt::Display for SyncJobItemStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "Queued"),
            Self::Converting => write!(f, "Converting"),
            Self::ReadyToTransfer => write!(f, "ReadyToTransfer"),
            Self::Transferring => write!(f, "Transferring"),
            Self::Synced => write!(f, "Synced"),
            Self::Failed => write!(f, "Failed"),
        }
    }
}

impl Default for SyncJobItemStatus {
    fn default() -> SyncJobItemStatus {
        Self::Queued
    }
}

