/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncJobRequest {
    #[serde(rename = "TargetId", skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
    #[serde(rename = "ItemIds", skip_serializing_if = "Option::is_none")]
    pub item_ids: Option<Vec<String>>,
    #[serde(rename = "Category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::SyncCategory>,
    #[serde(rename = "ParentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "Quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<String>,
    #[serde(rename = "Profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    #[serde(rename = "Container", skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
    #[serde(rename = "VideoCodec", skip_serializing_if = "Option::is_none")]
    pub video_codec: Option<String>,
    #[serde(rename = "AudioCodec", skip_serializing_if = "Option::is_none")]
    pub audio_codec: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "UnwatchedOnly", skip_serializing_if = "Option::is_none")]
    pub unwatched_only: Option<bool>,
    #[serde(rename = "SyncNewContent", skip_serializing_if = "Option::is_none")]
    pub sync_new_content: Option<bool>,
    #[serde(rename = "ItemLimit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_limit: Option<Option<i32>>,
    #[serde(rename = "Bitrate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bitrate: Option<Option<i32>>,
    #[serde(rename = "Downloaded", skip_serializing_if = "Option::is_none")]
    pub downloaded: Option<bool>,
}

impl SyncJobRequest {
    pub fn new() -> SyncJobRequest {
        SyncJobRequest {
            target_id: None,
            item_ids: None,
            category: None,
            parent_id: None,
            quality: None,
            profile: None,
            container: None,
            video_codec: None,
            audio_codec: None,
            name: None,
            user_id: None,
            unwatched_only: None,
            sync_new_content: None,
            item_limit: None,
            bitrate: None,
            downloaded: None,
        }
    }
}

