/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncedItem {
    #[serde(rename = "ServerId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "SyncJobId", skip_serializing_if = "Option::is_none")]
    pub sync_job_id: Option<i64>,
    #[serde(rename = "SyncJobName", skip_serializing_if = "Option::is_none")]
    pub sync_job_name: Option<String>,
    #[serde(rename = "SyncJobDateCreated", skip_serializing_if = "Option::is_none")]
    pub sync_job_date_created: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "SyncJobItemId", skip_serializing_if = "Option::is_none")]
    pub sync_job_item_id: Option<i64>,
    #[serde(rename = "OriginalFileName", skip_serializing_if = "Option::is_none")]
    pub original_file_name: Option<String>,
    #[serde(rename = "Item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::BaseItemDto>>,
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "AdditionalFiles", skip_serializing_if = "Option::is_none")]
    pub additional_files: Option<Vec<models::ItemFileInfo>>,
}

impl SyncedItem {
    pub fn new() -> SyncedItem {
        SyncedItem {
            server_id: None,
            sync_job_id: None,
            sync_job_name: None,
            sync_job_date_created: None,
            sync_job_item_id: None,
            original_file_name: None,
            item: None,
            user_id: None,
            additional_files: None,
        }
    }
}

