/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncCategory {
    #[serde(rename = "Latest")]
    Latest,
    #[serde(rename = "NextUp")]
    NextUp,
    #[serde(rename = "Resume")]
    Resume,

}

impl std::fmt::Display for SyncCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Latest => write!(f, "Latest"),
            Self::NextUp => write!(f, "NextUp"),
            Self::Resume => write!(f, "Resume"),
        }
    }
}

impl Default for SyncCategory {
    fn default() -> SyncCategory {
        Self::Latest
    }
}

