/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskInfo : Class TaskInfo  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskInfo {
    /// The name.
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "State", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::TaskState>,
    /// The progress.
    #[serde(rename = "CurrentProgressPercentage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_progress_percentage: Option<Option<f64>>,
    /// The id.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "LastExecutionResult", skip_serializing_if = "Option::is_none")]
    pub last_execution_result: Option<Box<models::TaskResult>>,
    /// The triggers.
    #[serde(rename = "Triggers", skip_serializing_if = "Option::is_none")]
    pub triggers: Option<Vec<models::TaskTriggerInfo>>,
    /// The description.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The category.
    #[serde(rename = "Category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// A value indicating whether this instance is hidden.
    #[serde(rename = "IsHidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
    /// The key.
    #[serde(rename = "Key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl TaskInfo {
    /// Class TaskInfo  
    pub fn new() -> TaskInfo {
        TaskInfo {
            name: None,
            state: None,
            current_progress_percentage: None,
            id: None,
            last_execution_result: None,
            triggers: None,
            description: None,
            category: None,
            is_hidden: None,
            key: None,
        }
    }
}

