/*
 * Emby Server REST API
 *
 * Explore the Emby Server API
 *
 * The version of the OpenAPI document: 4.9.5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskTriggerInfo : Class TaskTriggerInfo  
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskTriggerInfo {
    /// The type.
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The time of day.
    #[serde(rename = "TimeOfDayTicks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_of_day_ticks: Option<Option<i64>>,
    /// The interval.
    #[serde(rename = "IntervalTicks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interval_ticks: Option<Option<i64>>,
    #[serde(rename = "SystemEvent", skip_serializing_if = "Option::is_none")]
    pub system_event: Option<models::SystemEvent>,
    #[serde(rename = "DayOfWeek", skip_serializing_if = "Option::is_none")]
    pub day_of_week: Option<models::DayOfWeek>,
    /// The maximum runtime ticks.
    #[serde(rename = "MaxRuntimeTicks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_runtime_ticks: Option<Option<i64>>,
}

impl TaskTriggerInfo {
    /// Class TaskTriggerInfo  
    pub fn new() -> TaskTriggerInfo {
        TaskTriggerInfo {
            r#type: None,
            time_of_day_ticks: None,
            interval_ticks: None,
            system_event: None,
            day_of_week: None,
            max_runtime_ticks: None,
        }
    }
}

