/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`add_item_to_playlist`]
#[derive(Clone, Debug)]
pub struct AddItemToPlaylistParams {
    /// The playlist id.
    pub playlist_id: String,
    /// Item id, comma delimited.
    pub ids: Option<Vec<uuid::Uuid>>,
    /// Optional. 0-based index where to place the items or at the end if `null`.
    pub position: Option<i32>,
    /// The userId.
    pub user_id: Option<String>
}

/// struct for passing parameters to the method [`create_playlist`]
#[derive(Clone, Debug)]
pub struct CreatePlaylistParams {
    /// The playlist name.
    pub name: Option<String>,
    /// The item ids.
    pub ids: Option<Vec<uuid::Uuid>>,
    /// The user id.
    pub user_id: Option<String>,
    /// The media type.
    pub media_type: Option<String>,
    /// The create playlist payload.
    pub create_playlist_dto: Option<models::CreatePlaylistDto>
}

/// struct for passing parameters to the method [`get_playlist`]
#[derive(Clone, Debug)]
pub struct GetPlaylistParams {
    /// The playlist id.
    pub playlist_id: String
}

/// struct for passing parameters to the method [`get_playlist_items`]
#[derive(Clone, Debug)]
pub struct GetPlaylistItemsParams {
    /// The playlist id.
    pub playlist_id: String,
    /// User id.
    pub user_id: Option<String>,
    /// Optional. The record index to start at. All items with a lower index will be dropped from the results.
    pub start_index: Option<i32>,
    /// Optional. The maximum number of records to return.
    pub limit: Option<i32>,
    /// Optional. Specify additional fields of information to return in the output.
    pub fields: Option<Vec<models::ItemFields>>,
    /// Optional. Include image information in output.
    pub enable_images: Option<bool>,
    /// Optional. Include user data.
    pub enable_user_data: Option<bool>,
    /// Optional. The max number of images to return, per image type.
    pub image_type_limit: Option<i32>,
    /// Optional. The image types to include in the output.
    pub enable_image_types: Option<Vec<models::ImageType>>
}

/// struct for passing parameters to the method [`get_playlist_user`]
#[derive(Clone, Debug)]
pub struct GetPlaylistUserParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The user id.
    pub user_id: String
}

/// struct for passing parameters to the method [`get_playlist_users`]
#[derive(Clone, Debug)]
pub struct GetPlaylistUsersParams {
    /// The playlist id.
    pub playlist_id: String
}

/// struct for passing parameters to the method [`move_item`]
#[derive(Clone, Debug)]
pub struct MoveItemParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The item id.
    pub item_id: String,
    /// The new index.
    pub new_index: i32
}

/// struct for passing parameters to the method [`remove_item_from_playlist`]
#[derive(Clone, Debug)]
pub struct RemoveItemFromPlaylistParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The item ids, comma delimited.
    pub entry_ids: Option<Vec<String>>
}

/// struct for passing parameters to the method [`remove_user_from_playlist`]
#[derive(Clone, Debug)]
pub struct RemoveUserFromPlaylistParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The user id.
    pub user_id: String
}

/// struct for passing parameters to the method [`update_playlist`]
#[derive(Clone, Debug)]
pub struct UpdatePlaylistParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The Jellyfin.Api.Models.PlaylistDtos.UpdatePlaylistDto id.
    pub update_playlist_dto: models::UpdatePlaylistDto
}

/// struct for passing parameters to the method [`update_playlist_user`]
#[derive(Clone, Debug)]
pub struct UpdatePlaylistUserParams {
    /// The playlist id.
    pub playlist_id: String,
    /// The user id.
    pub user_id: String,
    /// The Jellyfin.Api.Models.PlaylistDtos.UpdatePlaylistUserDto.
    pub update_playlist_user_dto: models::UpdatePlaylistUserDto
}


/// struct for typed errors of method [`add_item_to_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddItemToPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePlaylistError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_items`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistItemsError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistUserError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistUsersError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`move_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MoveItemError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_item_from_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveItemFromPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_user_from_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveUserFromPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status401(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_playlist_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePlaylistUserError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}


pub async fn add_item_to_playlist(configuration: &configuration::Configuration, params: AddItemToPlaylistParams) -> Result<(), Error<AddItemToPlaylistError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = params.ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.position {
        req_builder = req_builder.query(&[("position", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AddItemToPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// For backwards compatibility parameters can be sent via Query or Body, with Query having higher precedence. Query parameters are obsolete.
pub async fn create_playlist(configuration: &configuration::Configuration, params: CreatePlaylistParams) -> Result<models::PlaylistCreationResult, Error<CreatePlaylistError>> {

    let uri_str = format!("{}/Playlists", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = params.name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.media_type {
        req_builder = req_builder.query(&[("mediaType", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.create_playlist_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistCreationResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistCreationResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist(configuration: &configuration::Configuration, params: GetPlaylistParams) -> Result<models::PlaylistDto, Error<GetPlaylistError>> {

    let uri_str = format!("{}/Playlists/{playlistId}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_items(configuration: &configuration::Configuration, params: GetPlaylistItemsParams) -> Result<models::BaseItemDtoQueryResult, Error<GetPlaylistItemsError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistItemsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_user(configuration: &configuration::Configuration, params: GetPlaylistUserParams) -> Result<models::PlaylistUserPermissions, Error<GetPlaylistUserError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id), userId=crate::apis::urlencode(params.user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistUserPermissions`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistUserPermissions`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_users(configuration: &configuration::Configuration, params: GetPlaylistUsersParams) -> Result<Vec<models::PlaylistUserPermissions>, Error<GetPlaylistUsersError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Users", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::PlaylistUserPermissions&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::PlaylistUserPermissions&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn move_item(configuration: &configuration::Configuration, params: MoveItemParams) -> Result<(), Error<MoveItemError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id), itemId=crate::apis::urlencode(params.item_id), newIndex=params.new_index);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MoveItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_item_from_playlist(configuration: &configuration::Configuration, params: RemoveItemFromPlaylistParams) -> Result<(), Error<RemoveItemFromPlaylistError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = params.entry_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("entryIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("entryIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveItemFromPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_user_from_playlist(configuration: &configuration::Configuration, params: RemoveUserFromPlaylistParams) -> Result<(), Error<RemoveUserFromPlaylistError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id), userId=crate::apis::urlencode(params.user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveUserFromPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_playlist(configuration: &configuration::Configuration, params: UpdatePlaylistParams) -> Result<(), Error<UpdatePlaylistError>> {

    let uri_str = format!("{}/Playlists/{playlistId}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.update_playlist_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_playlist_user(configuration: &configuration::Configuration, params: UpdatePlaylistUserParams) -> Result<(), Error<UpdatePlaylistUserError>> {

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(params.playlist_id), userId=crate::apis::urlencode(params.user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.update_playlist_user_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePlaylistUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

