/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.11.11
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_episodes`]
#[derive(Clone, Debug)]
pub struct GetEpisodesParams {
    /// The series id.
    pub series_id: String,
    /// The user id.
    pub user_id: Option<String>,
    /// Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines, TrailerUrls.
    pub fields: Option<Vec<models::ItemFields>>,
    /// Optional filter by season number.
    pub season: Option<i32>,
    /// Optional. Filter by season id.
    pub season_id: Option<String>,
    /// Optional. Filter by items that are missing episodes or not.
    pub is_missing: Option<bool>,
    /// Optional. Return items that are siblings of a supplied item.
    pub adjacent_to: Option<String>,
    /// Optional. Skip through the list until a given item is found.
    pub start_item_id: Option<String>,
    /// Optional. The record index to start at. All items with a lower index will be dropped from the results.
    pub start_index: Option<i32>,
    /// Optional. The maximum number of records to return.
    pub limit: Option<i32>,
    /// Optional, include image information in output.
    pub enable_images: Option<bool>,
    /// Optional, the max number of images to return, per image type.
    pub image_type_limit: Option<i32>,
    /// Optional. The image types to include in the output.
    pub enable_image_types: Option<Vec<models::ImageType>>,
    /// Optional. Include user data.
    pub enable_user_data: Option<bool>,
    /// Optional. Specify one or more sort orders, comma delimited. Options: Album, AlbumArtist, Artist, Budget, CommunityRating, CriticRating, DateCreated, DatePlayed, PlayCount, PremiereDate, ProductionYear, SortName, Random, Revenue, Runtime.
    pub sort_by: Option<String>
}

/// struct for passing parameters to the method [`get_next_up`]
#[derive(Clone, Debug)]
pub struct GetNextUpParams {
    /// The user id of the user to get the next up episodes for.
    pub user_id: Option<String>,
    /// Optional. The record index to start at. All items with a lower index will be dropped from the results.
    pub start_index: Option<i32>,
    /// Optional. The maximum number of records to return.
    pub limit: Option<i32>,
    /// Optional. Specify additional fields of information to return in the output.
    pub fields: Option<Vec<models::ItemFields>>,
    /// Optional. Filter by series id.
    pub series_id: Option<String>,
    /// Optional. Specify this to localize the search to a specific item or folder. Omit to use the root.
    pub parent_id: Option<String>,
    /// Optional. Include image information in output.
    pub enable_images: Option<bool>,
    /// Optional. The max number of images to return, per image type.
    pub image_type_limit: Option<i32>,
    /// Optional. The image types to include in the output.
    pub enable_image_types: Option<Vec<models::ImageType>>,
    /// Optional. Include user data.
    pub enable_user_data: Option<bool>,
    /// Optional. Starting date of shows to show in Next Up section.
    pub next_up_date_cutoff: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Whether to enable the total records count. Defaults to true.
    pub enable_total_record_count: Option<bool>,
    /// Whether to disable sending the first episode in a series as next up.
    pub disable_first_episode: Option<bool>,
    /// Whether to include resumable episodes in next up results.
    pub enable_resumable: Option<bool>,
    /// Whether to include watched episodes in next up results.
    pub enable_rewatching: Option<bool>
}

/// struct for passing parameters to the method [`get_seasons`]
#[derive(Clone, Debug)]
pub struct GetSeasonsParams {
    /// The series id.
    pub series_id: String,
    /// The user id.
    pub user_id: Option<String>,
    /// Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines, TrailerUrls.
    pub fields: Option<Vec<models::ItemFields>>,
    /// Optional. Filter by special season.
    pub is_special_season: Option<bool>,
    /// Optional. Filter by items that are missing episodes or not.
    pub is_missing: Option<bool>,
    /// Optional. Return items that are siblings of a supplied item.
    pub adjacent_to: Option<String>,
    /// Optional. Include image information in output.
    pub enable_images: Option<bool>,
    /// Optional. The max number of images to return, per image type.
    pub image_type_limit: Option<i32>,
    /// Optional. The image types to include in the output.
    pub enable_image_types: Option<Vec<models::ImageType>>,
    /// Optional. Include user data.
    pub enable_user_data: Option<bool>
}

/// struct for passing parameters to the method [`get_upcoming_episodes`]
#[derive(Clone, Debug)]
pub struct GetUpcomingEpisodesParams {
    /// The user id of the user to get the upcoming episodes for.
    pub user_id: Option<String>,
    /// Optional. The record index to start at. All items with a lower index will be dropped from the results.
    pub start_index: Option<i32>,
    /// Optional. The maximum number of records to return.
    pub limit: Option<i32>,
    /// Optional. Specify additional fields of information to return in the output.
    pub fields: Option<Vec<models::ItemFields>>,
    /// Optional. Specify this to localize the search to a specific item or folder. Omit to use the root.
    pub parent_id: Option<String>,
    /// Optional. Include image information in output.
    pub enable_images: Option<bool>,
    /// Optional. The max number of images to return, per image type.
    pub image_type_limit: Option<i32>,
    /// Optional. The image types to include in the output.
    pub enable_image_types: Option<Vec<models::ImageType>>,
    /// Optional. Include user data.
    pub enable_user_data: Option<bool>
}


/// struct for typed errors of method [`get_episodes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEpisodesError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_next_up`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNextUpError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_seasons`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSeasonsError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_upcoming_episodes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUpcomingEpisodesError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn get_episodes(configuration: &configuration::Configuration, params: GetEpisodesParams) -> Result<models::BaseItemDtoQueryResult, Error<GetEpisodesError>> {

    let uri_str = format!("{}/Shows/{seriesId}/Episodes", configuration.base_path, seriesId=crate::apis::urlencode(params.series_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.season {
        req_builder = req_builder.query(&[("season", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.season_id {
        req_builder = req_builder.query(&[("seasonId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.is_missing {
        req_builder = req_builder.query(&[("isMissing", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.adjacent_to {
        req_builder = req_builder.query(&[("adjacentTo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_item_id {
        req_builder = req_builder.query(&[("startItemId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEpisodesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_next_up(configuration: &configuration::Configuration, params: GetNextUpParams) -> Result<models::BaseItemDtoQueryResult, Error<GetNextUpError>> {

    let uri_str = format!("{}/Shows/NextUp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.series_id {
        req_builder = req_builder.query(&[("seriesId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.parent_id {
        req_builder = req_builder.query(&[("parentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.next_up_date_cutoff {
        req_builder = req_builder.query(&[("nextUpDateCutoff", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_total_record_count {
        req_builder = req_builder.query(&[("enableTotalRecordCount", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.disable_first_episode {
        req_builder = req_builder.query(&[("disableFirstEpisode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_resumable {
        req_builder = req_builder.query(&[("enableResumable", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_rewatching {
        req_builder = req_builder.query(&[("enableRewatching", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetNextUpError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_seasons(configuration: &configuration::Configuration, params: GetSeasonsParams) -> Result<models::BaseItemDtoQueryResult, Error<GetSeasonsError>> {

    let uri_str = format!("{}/Shows/{seriesId}/Seasons", configuration.base_path, seriesId=crate::apis::urlencode(params.series_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.is_special_season {
        req_builder = req_builder.query(&[("isSpecialSeason", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.is_missing {
        req_builder = req_builder.query(&[("isMissing", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.adjacent_to {
        req_builder = req_builder.query(&[("adjacentTo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSeasonsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_upcoming_episodes(configuration: &configuration::Configuration, params: GetUpcomingEpisodesParams) -> Result<models::BaseItemDtoQueryResult, Error<GetUpcomingEpisodesError>> {

    let uri_str = format!("{}/Shows/Upcoming", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.parent_id {
        req_builder = req_builder.query(&[("parentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetUpcomingEpisodesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

