/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.11.11
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_universal_audio_stream`]
#[derive(Clone, Debug)]
pub struct GetUniversalAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// Optional. The audio container.
    pub container: Option<Vec<String>>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. The user id.
    pub user_id: Option<String>,
    /// Optional. The audio codec to transcode to.
    pub audio_codec: Option<String>,
    /// Optional. The maximum number of audio channels.
    pub max_audio_channels: Option<i32>,
    /// Optional. The number of how many audio channels to transcode to.
    pub transcoding_audio_channels: Option<i32>,
    /// Optional. The maximum streaming bitrate.
    pub max_streaming_bitrate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The container to transcode to.
    pub transcoding_container: Option<String>,
    /// Optional. The transcoding protocol.
    pub transcoding_protocol: Option<String>,
    /// Optional. The maximum audio sample rate.
    pub max_audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Whether to enable remote media.
    pub enable_remote_media: Option<bool>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>,
    /// Optional. Whether to break on non key frames.
    pub break_on_non_key_frames: Option<bool>,
    /// Whether to enable redirection. Defaults to true.
    pub enable_redirection: Option<bool>
}

/// struct for passing parameters to the method [`head_universal_audio_stream`]
#[derive(Clone, Debug)]
pub struct HeadUniversalAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// Optional. The audio container.
    pub container: Option<Vec<String>>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. The user id.
    pub user_id: Option<String>,
    /// Optional. The audio codec to transcode to.
    pub audio_codec: Option<String>,
    /// Optional. The maximum number of audio channels.
    pub max_audio_channels: Option<i32>,
    /// Optional. The number of how many audio channels to transcode to.
    pub transcoding_audio_channels: Option<i32>,
    /// Optional. The maximum streaming bitrate.
    pub max_streaming_bitrate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The container to transcode to.
    pub transcoding_container: Option<String>,
    /// Optional. The transcoding protocol.
    pub transcoding_protocol: Option<String>,
    /// Optional. The maximum audio sample rate.
    pub max_audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Whether to enable remote media.
    pub enable_remote_media: Option<bool>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>,
    /// Optional. Whether to break on non key frames.
    pub break_on_non_key_frames: Option<bool>,
    /// Whether to enable redirection. Defaults to true.
    pub enable_redirection: Option<bool>
}


/// struct for typed errors of method [`get_universal_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUniversalAudioStreamError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`head_universal_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadUniversalAudioStreamError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn get_universal_audio_stream(configuration: &configuration::Configuration, params: GetUniversalAudioStreamParams) -> Result<reqwest::Response, Error<GetUniversalAudioStreamError>> {

    let uri_str = format!("{}/Audio/{itemId}/universal", configuration.base_path, itemId=crate::apis::urlencode(params.item_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.container {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("container".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("container", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.media_source_id {
        req_builder = req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("deviceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("audioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_audio_channels {
        req_builder = req_builder.query(&[("transcodingAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_streaming_bitrate {
        req_builder = req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("audioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_container {
        req_builder = req_builder.query(&[("transcodingContainer", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_protocol {
        req_builder = req_builder.query(&[("transcodingProtocol", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_sample_rate {
        req_builder = req_builder.query(&[("maxAudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_bit_depth {
        req_builder = req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_remote_media {
        req_builder = req_builder.query(&[("enableRemoteMedia", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_audio_vbr_encoding {
        req_builder = req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.break_on_non_key_frames {
        req_builder = req_builder.query(&[("breakOnNonKeyFrames", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_redirection {
        req_builder = req_builder.query(&[("enableRedirection", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetUniversalAudioStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn head_universal_audio_stream(configuration: &configuration::Configuration, params: HeadUniversalAudioStreamParams) -> Result<reqwest::Response, Error<HeadUniversalAudioStreamError>> {

    let uri_str = format!("{}/Audio/{itemId}/universal", configuration.base_path, itemId=crate::apis::urlencode(params.item_id));
    let mut req_builder = configuration.client.request(reqwest::Method::HEAD, &uri_str);

    if let Some(ref param_value) = params.container {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("container".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("container", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = params.media_source_id {
        req_builder = req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.device_id {
        req_builder = req_builder.query(&[("deviceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_codec {
        req_builder = req_builder.query(&[("audioCodec", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_channels {
        req_builder = req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_audio_channels {
        req_builder = req_builder.query(&[("transcodingAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_streaming_bitrate {
        req_builder = req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.audio_bit_rate {
        req_builder = req_builder.query(&[("audioBitRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.start_time_ticks {
        req_builder = req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_container {
        req_builder = req_builder.query(&[("transcodingContainer", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.transcoding_protocol {
        req_builder = req_builder.query(&[("transcodingProtocol", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_sample_rate {
        req_builder = req_builder.query(&[("maxAudioSampleRate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max_audio_bit_depth {
        req_builder = req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_remote_media {
        req_builder = req_builder.query(&[("enableRemoteMedia", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_audio_vbr_encoding {
        req_builder = req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.break_on_non_key_frames {
        req_builder = req_builder.query(&[("breakOnNonKeyFrames", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.enable_redirection {
        req_builder = req_builder.query(&[("enableRedirection", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<HeadUniversalAudioStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

