/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackupRestoreRequestDto : Defines properties used to start a restore process.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupRestoreRequestDto {
    /// Gets or Sets the name of the backup archive to restore from. Must be present in MediaBrowser.Common.Configuration.IApplicationPaths.BackupPath.
    #[serde(rename = "ArchiveFileName")]
    pub archive_file_name: String,
}

impl BackupRestoreRequestDto {
    /// Defines properties used to start a restore process.
    pub fn new(archive_file_name: String) -> BackupRestoreRequestDto {
        BackupRestoreRequestDto {
            archive_file_name,
        }
    }
}

