/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CastReceiverApplication : The cast receiver application model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CastReceiverApplication {
    /// Gets or sets the cast receiver application id.
    #[serde(rename = "Id")]
    pub id: String,
    /// Gets or sets the cast receiver application name.
    #[serde(rename = "Name")]
    pub name: String,
}

impl CastReceiverApplication {
    /// The cast receiver application model.
    pub fn new(id: String, name: String) -> CastReceiverApplication {
        CastReceiverApplication {
            id,
            name,
        }
    }
}

