/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HlsAudioSeekStrategy : An enum representing the options to seek the input audio stream when transcoding HLS segments.
/// An enum representing the options to seek the input audio stream when transcoding HLS segments.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HlsAudioSeekStrategy {
    #[serde(rename = "TrimCopiedAudio")]
    TrimCopiedAudio,
    #[serde(rename = "TranscodeAudio")]
    TranscodeAudio,

}

impl std::fmt::Display for HlsAudioSeekStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TrimCopiedAudio => write!(f, "TrimCopiedAudio"),
            Self::TranscodeAudio => write!(f, "TranscodeAudio"),
        }
    }
}

impl Default for HlsAudioSeekStrategy {
    fn default() -> HlsAudioSeekStrategy {
        Self::TrimCopiedAudio
    }
}

