/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParentalRatingScore : A class representing an parental rating score.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentalRatingScore {
    /// Gets or sets the score.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
    /// Gets or sets the sub score.
    #[serde(rename = "subScore", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sub_score: Option<Option<i32>>,
}

impl ParentalRatingScore {
    /// A class representing an parental rating score.
    pub fn new() -> ParentalRatingScore {
        ParentalRatingScore {
            score: None,
            sub_score: None,
        }
    }
}

