/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueueItem : An item in a play queue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueItem {
    /// Gets or sets the item id.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Gets or sets the playlist item id.
    #[serde(rename = "PlaylistItemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub playlist_item_id: Option<Option<String>>,
}

impl QueueItem {
    /// An item in a play queue.
    pub fn new() -> QueueItem {
        QueueItem {
            id: None,
            playlist_item_id: None,
        }
    }
}

