/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncPlayStateUpdate {
    /// Gets the group identifier.
    #[serde(rename = "GroupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<uuid::Uuid>,
    /// Gets the update data.
    #[serde(rename = "Data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GroupStateUpdate>>,
    /// Enum GroupUpdateType.
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::GroupUpdateType>,
}

impl SyncPlayStateUpdate {
    pub fn new() -> SyncPlayStateUpdate {
        SyncPlayStateUpdate {
            group_id: None,
            data: None,
            r#type: None,
        }
    }
}

