/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.11.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VideoRangeType : An enum representing types of video ranges.
/// An enum representing types of video ranges.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VideoRangeType {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "SDR")]
    Sdr,
    #[serde(rename = "HDR10")]
    Hdr10,
    #[serde(rename = "HLG")]
    Hlg,
    #[serde(rename = "DOVI")]
    Dovi,
    #[serde(rename = "DOVIWithHDR10")]
    DoviWithHdr10,
    #[serde(rename = "DOVIWithHLG")]
    DoviWithHlg,
    #[serde(rename = "DOVIWithSDR")]
    DoviWithSdr,
    #[serde(rename = "DOVIWithEL")]
    DoviWithEl,
    #[serde(rename = "DOVIWithHDR10Plus")]
    DoviWithHdr10Plus,
    #[serde(rename = "DOVIWithELHDR10Plus")]
    DoviWithElhdr10Plus,
    #[serde(rename = "DOVIInvalid")]
    DoviInvalid,
    #[serde(rename = "HDR10Plus")]
    Hdr10Plus,

}

impl std::fmt::Display for VideoRangeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "Unknown"),
            Self::Sdr => write!(f, "SDR"),
            Self::Hdr10 => write!(f, "HDR10"),
            Self::Hlg => write!(f, "HLG"),
            Self::Dovi => write!(f, "DOVI"),
            Self::DoviWithHdr10 => write!(f, "DOVIWithHDR10"),
            Self::DoviWithHlg => write!(f, "DOVIWithHLG"),
            Self::DoviWithSdr => write!(f, "DOVIWithSDR"),
            Self::DoviWithEl => write!(f, "DOVIWithEL"),
            Self::DoviWithHdr10Plus => write!(f, "DOVIWithHDR10Plus"),
            Self::DoviWithElhdr10Plus => write!(f, "DOVIWithELHDR10Plus"),
            Self::DoviInvalid => write!(f, "DOVIInvalid"),
            Self::Hdr10Plus => write!(f, "HDR10Plus"),
        }
    }
}

impl Default for VideoRangeType {
    fn default() -> VideoRangeType {
        Self::Unknown
    }
}

